Voucher Wheel v1.1/Main/wheel/app/urls.py
"""
APP's local routes
"""
from django.urls import path

from . import views

app_name = 'wheel'

urlpatterns = [
    path('', views.index, name='index'),
    path('draw', views.draw_spin, name='draw_spin'),
    path('<int:pk>', views.draw_result, name='draw_result'),
]

Voucher Wheel v1.1/Main/wheel/core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

Voucher Wheel v1.1/Main/wheel/app/models.py
import logging
import secrets

from django.db import models
from django.db.models.signals import post_save

# Get an instance of a logger
logger = logging.getLogger(__name__)


class Draw(models.Model):
    """
    Class to represent each valid draw that happened in the system.
    """
    email = models.EmailField()
    code = models.CharField(max_length=8)
    sent = models.BooleanField(default=False)
    rotation = models.IntegerField(default=0)
    date = models.DateTimeField(blank=True, null=True)
    prize = models.ForeignKey('Prize', on_delete=models.CASCADE, null=False, blank=False)
    retry_used = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.email} - {self.code}"

    def use_retry(self):
        logger.info("use_retry!!!!!")
        self.retry_used = True
        self.save()


class UniqueCode(models.Model):
    """
    Class to create human friendly gift/coupon/voucher codes.
    """
    # Model field for our unique code
    code = models.CharField(max_length=8, blank=True, null=True, unique=True, default="Automatic Generated", editable=False)
    used = models.BooleanField(default=False)
    date = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        """
        Connected to the post_save signal of the UniqueCodes model. This is used to set the
        code once we have created the db instance and have access to the primary key (ID Field).
        """
        # If new database record
        if created:
            # We have the primary key (ID Field) now so let's grab it
            id_string = str(instance.id)
            # Define our random string alphabet
            # (notice I've omitted I,O,etc. as they can be confused for other characters)
            upper_alpha = "ABCDEFGHJKLMNPQRSTVWXYZ"
            # Create an 8 char random string from our alphabet
            random_str = "".join(secrets.choice(upper_alpha) for i in range(8))
            # Append the ID to the end of the random string
            instance.code = (random_str + id_string)[-8:]
            # Save the class instance
            instance.save()

    def __str__(self):
        return f"{self.code} [Used: {self.used}]"


# Connect the post_create function to the UniqueCodes post_save signal
post_save.connect(UniqueCode.post_create, sender=UniqueCode)


class Prize(models.Model):
    """
    Class to represent each available prize in the wheel.
    """
    label = models.CharField(max_length=12)
    winner = models.BooleanField(default=False)
    try_again = models.BooleanField(default=False)

    def __str__(self):
        return self.label

Voucher Wheel v1.1/Main/wheel/app/forms.py
from django import forms

from app.draw import is_code_valid
from app.models import Draw
from django import template

register = template.Library()


@register.filter(name='addclass')
def addclass(field, css):
    return field.as_widget(attrs={"class": css})


class DrawForm(forms.ModelForm):
    class Meta:
        model = Draw
        fields = ('email', 'code',)

    def clean(self):
        cleaned_data = super().clean()
        code = cleaned_data.get("code")

        if is_code_valid(code) is not True:
            self.add_error('code', forms.ValidationError("Invalid or expired code!"))

Voucher Wheel v1.1/Main/wheel/app/views.py
import logging

from app.draw import calc_wheel_rotations, get_prize_result, is_code_valid, set_code_used, get_prize
from app.forms import DrawForm
from app.models import Draw, Prize
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.utils import timezone

# Get an instance of a logger
logger = logging.getLogger(__name__)


def draw_spin(request):
    logger.info(f"Draw_new with {request.method}")
    prizes = get_list_or_404(Prize)

    if request.method == "POST":
        form = DrawForm(request.POST)

        if form.is_valid(): # and code is valid (checked on form class)
            email = form.cleaned_data['email']
            code = form.cleaned_data['code']
            logger.info(f"email [{email}] code [{code}]")

            instance = form.save(commit=False)
            instance.date = timezone.now()
            instance.rotation = calc_wheel_rotations()
            instance.prize = get_prize(get_prize_result(instance.rotation))
            instance.save()

            set_code_used(code, True)

            return render(request, 'index.html',
                          {'spin': True, 'result': instance.pk, 'rotation': instance.rotation, 'prizes': prizes})
        else:  # invalid form
            logger.warning(f"invalid form else => {form.is_valid()}")
            logger.warning(f"invalid form else => {form.errors}")
            form = DrawForm(request.POST)
    else:
        form = DrawForm()  # No post data

    return render(request, 'index.html', {'form': form, 'prizes': prizes})


def draw_result(request, pk):
    prizes = get_list_or_404(Prize)
    draw = get_object_or_404(Draw, pk=pk)
    logger.info(f"Draw with {request.method} for id {draw.pk}")

    prize = get_prize(draw.prize.pk)
    logger.info(f"Prize {prize.pk}, {prize.label}, {prize.winner}")

    if prize.try_again:
        set_code_used(draw.code, False)

    return render(request, 'draw.html', {'prizes': prizes, 'result_draw': draw, 'result_prize': prize})


def index(request):
    form = DrawForm()
    prizes = get_list_or_404(Prize)

    return render(request, 'index.html',
                  {'form': form, 'prizes': prizes})

Voucher Wheel v1.1/Main/wheel/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Voucher Wheel</title>
  <meta charset="UTF-8"/>
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicon.ico/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicon.ico/apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon.ico/apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon.ico/apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon.ico/apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicon.ico/apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicon.ico/apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicon.ico/apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon.ico/apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/favicon.ico/android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon.ico/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.ico/favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon.ico/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'img/favicon.ico/manifest.json' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="{% static 'img/favicon.ico/ms-icon-144x144.png' %}">

  <style>
      body {
          background-color: #002535;
      }
  </style>
</head>

<body class="text-center">

<div class="row h-100 mx-auto" style="max-width: 1536px;">
  <!-- Wheel -->
  <div class="col-sm-7 my-auto">
    <div class="row no-gutters no-border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col d-flex flex-column position-static">
        <div id="chart"></div>
      </div>
    </div>
  </div>

  <!-- Form -->
  <div class="col-sm-5 my-auto">
    <div class="row no-gutters no-border rounded overflow-hidden flex-md-row mb-4 ml-4 mr-4 shadow-sm h-md-250 position-relative">
    <div class="container">
      <a href="{% url 'wheel:index' %}">
        <img alt="Voucher Wheel logo" class="mx-auto d-block img-fluid" src="{% static 'img/logo.png' %}">
      </a>
      {% block content %}{% endblock %}
      <p class="mt-3 mb-3 text-muted"><a href="http://www.visiansystems.com/">Visian Systems</a> © 2021</p>
    </div>
  </div>
  </div>
</div>


<script charset="utf-8" src="https://d3js.org/d3.v3.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script src="{% static 'js/confetti.js' %}"></script>

<script type="text/javascript">
    console.log("Populating prizes....");

    let prizes = [
        {% for prize in prizes %}
            {% if not forloop.first %},{% endif %}
            {
                label: "{{ prize.label }}",
                winner: {{ prize.winner | lower }}
            }
        {% endfor %}
    ];

</script>
{# Need to be load after the prizes array is defined #}
<script src="{% static 'js/script.js' %}"></script>

{% block extra-scripts %}{% endblock %}

</body>
</html>

Voucher Wheel v1.1/Main/wheel/templates/draw.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% if result_prize.winner %}
    <h1 class="blinking h1 mt-2 mb-5 font-weight-normal" style="color: white; text-transform:uppercase;">
      Congratulations!!</h1>

    <h4 class="h4 mb-4 font-weight-normal" style="color: white;">
      The administrator is already aware of your prize and will contact you shortly to let you know how to receive it.
      Your details were successfully stored:</h4>

    <div class="card mb-4">
      <div class="card-body">
        <p style="color: black" class="col-form-label col-form-label-lg">email: {{ result_draw.email }}</p>
        <p style="color: black" class="col-form-label col-form-label-lg">prize: {{ result_prize.label }}</p>
      </div>
    </div>

  {% else %}
    {% if result_prize.try_again and not result_draw.retry_used %}
      <h1 class="blinking h1 mt-2 mb-5 font-weight-normal" style="color: white; text-transform:uppercase;">Try
        again!</h1>
    {% else %}
      <h1 class="h1 mt-2 mb-5 font-weight-normal" style="color: white; text-transform:uppercase;">Better luck next
        time!</h1>
    {% endif %}
  {% endif %}


  {% if result_prize.try_again and not result_draw.retry_used %}
    {% if result_draw.retry_used %}
      <h4 class="h4 mb-5 font-weight-normal" style="color: white;">
        Your retry was already used...</h4>
    {% else %}
      {{ result_draw.use_retry }}

      <h4 class="h4 mb-5 font-weight-normal" style="color: white;">
        You have just won a free spin! Please click on the button below to try again!</h4>

      <div class="mt-5">
        <form class="form-signin" method="POST" action="{% url 'wheel:draw_spin' %}">
          {% csrf_token %}
          <input type="hidden" name="email" maxlength="254" class="form-control form-control-lg" required=""
                 id="id_email" value="{{ result_draw.email }}">
          <input type="hidden" name="code" maxlength="8" class="form-control form-control-lg" required="" id="id_code"
                 value="{{ result_draw.code }}">
          <button class="mt2 btn btn-lg btn-primary btn-block" type="submit">Spin again for free!</button>
        </form>
      </div>
    {% endif %}

  {% else %} <!-- LOSER -->
    {% if result_draw.retry_used %}
      <h4 class="h4 mb-5 font-weight-normal" style="color: white;">
        Your retry was already used...</h4>
    {% endif %}
    <h4 class="h4 mb-5 font-weight-normal" style="color: white;">
      If you have more code vouchers to use, please click on the button below to return to the main page.</h4>

    <div class="mt-5">
      <form action="{% url 'wheel:index' %}">
        <button class="mt2 btn btn-lg btn-primary btn-block" type="submit">Enter a new code!</button>
      </form>

    </div>
  {% endif %}

{% endblock %}

{% block extra-scripts %}
  <script type="text/javascript">
      {% if result_prize.winner %}
          confetti.start();
      {% endif %}

      console.log("Return to result", {{ result_draw.rotation }});
      spinToResult({{ result_draw.rotation }});
  </script>
{% endblock %}

Voucher Wheel v1.1/Main/wheel/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

  <div style="margin:20px 0 25px 0;">

    <h1 class="h1 mt-2 mb-5 font-weight-normal" style="color: white;
        text-transform:uppercase;">Spin the wheel to win!</h1>

    {% if error %}
      <h4 class="h4 mb-5 font-weight-normal" style="color: white;">ERROR: {{ error }}</h4>
    {% endif %}

    {% if spin %}
      <h4 class="h4 mb-5 font-weight-normal" style="color: white;">Good luck!</h4>
    {% else %}
      <p class="h4 mb-5 font-weight-normal" style="color: white;">Enter your code below to spin the wheel for a
        chance to win!</p>

      <form class="form-signin" method="POST" action="{% url 'wheel:draw_spin' %}">
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group row">
            <label style="color: white"
                   class="col-sm-2 col-form-label col-form-label-lg"
                   for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field|add_class:'form-control form-control-lg' }}
              {% if field.errors  %}
                <div class="alert alert-danger mt-3" role="alert">{{ field.errors.0 }}</div>
              {% endif %}
            </div>
          </div>
        {% endfor %}
        <div class="mt-5">
          <button class="mt2 btn btn-lg btn-primary btn-block" type="submit">SPIN!</button>
        </div>
      </form>
    {% endif %}

  </div>
{% endblock %}

{% block extra-scripts %}
  {% if spin %}
    <script type="text/javascript">
        console.log("Spin the Wheel!", {{ result }});
        spin("{% url 'wheel:draw_result' result %}", {{ rotation }});
    </script>
  {% else %}
    <script type="text/javascript">
    {#introRotation(false);#}
      </script>
  {% endif %}

{% endblock %}